[workspace]
members = ["crates/memweft-types", "crates/memweft-store", "crates/memweft-ffi", "crates/memweft", "crates/memweft-learning", "crates/memweft-node"]
default-members = ["crates/memweft-types", "crates/memweft-store", "crates/memweft", "crates/memweft-learning"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "Apache-2.0"

[patch.crates-io]
subprocess = { path = "vendor/subprocess" }
libsqlite3-sys = { path = "vendor/libsqlite3-sys" }
