"""Offline metadata and failure-path tests; no package builds or installations."""
import contextlib
import importlib.util
import io
import json
from pathlib import Path
import subprocess
import tarfile
import tempfile
import unittest
from unittest.mock import patch
import zipfile


SPEC = importlib.util.spec_from_file_location("verify_packages", Path(__file__).resolve().parents[1] / "verify_packages.py")
verify = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(verify)


class PackageVerificationTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        self.addCleanup(self.temporary.cleanup)

    def wheel(self, extra=()):
        wheel = self.root / "memweft-0.2.0a1-cp311-cp311-test.whl"
        with zipfile.ZipFile(wheel, "w") as archive:
            files = {
                "memweft/__init__.py": "", "memweft/_core.so": "placeholder",
                "memweft-0.2.0a1.dist-info/licenses/LICENSE": "license text",
                "memweft-0.2.0a1.dist-info/METADATA": "Name: memweft\nVersion: 0.2.0a1\n",
            }
            files.update(dict(extra))
            for name, content in files.items():
                archive.writestr(name, content)
        return wheel

    def npm(self, missing=None, version="0.2.0-alpha.1"):
        tarball = self.root / "memweft-0.2.0-alpha.1.tgz"
        with tarfile.open(tarball, "w:gz") as archive:
            files = {
                "package/package.json": json.dumps({"name":"memweft", "version":version}),
                "package/LICENSE": "license", "package/dist/index.js": "",
                "package/dist/index.d.ts": "", "package/dist/langgraph.js": "",
                "package/dist/langgraph.d.ts": "", "package/native/memweft.node": "placeholder",
            }
            for name, content in files.items():
                if name == missing:
                    continue
                raw = content.encode()
                member = tarfile.TarInfo(name)
                member.size = len(raw)
                archive.addfile(member, io.BytesIO(raw))
        return tarball

    def build_record(self, artifact, digest=None, commit="a" * 40, dirty=False):
        path = self.root / "build-record.json"
        path.write_text(json.dumps({
            "build": {"source": {"commit_sha":commit, "dirty":dirty}, "workflow_sha256":"c" * 64,
                "github":{"run_id":"123", "run_attempt":"2", "job":"python-wheel"}},
            "artifacts": {artifact.name: digest or verify.sha256(artifact)},
        }))
        return path

    def test_versions_come_from_archive_metadata(self):
        self.assertEqual(verify.wheel_metadata(self.wheel()), {"name":"memweft", "version":"0.2.0a1"})
        self.assertEqual(verify.npm_metadata(self.npm()), {"name":"memweft", "version":"0.2.0-alpha.1"})

    def test_archive_integrity_remains_required(self):
        with self.assertRaisesRegex(AssertionError, "generated bytecode"):
            verify.wheel_metadata(self.wheel([("memweft/__pycache__/api.pyc", "bad")]))
        with self.assertRaisesRegex(AssertionError, "exactly one native extension"):
            verify.wheel_metadata(self.wheel([("memweft/_core.pyd", "second native")]))
        with self.assertRaisesRegex(AssertionError, "missing package/native"):
            verify.npm_metadata(self.npm(missing="package/native/memweft.node"))
        with self.assertRaisesRegex(AssertionError, "no version"):
            verify.npm_metadata(self.npm(version=""))

    def test_unrecorded_build_never_infers_current_head(self):
        provenance = verify.build_provenance(None, self.wheel(), "e" * 64)
        self.assertEqual(provenance["status"], "not_recorded")
        self.assertEqual(provenance["source"], {"commit_sha":None, "dirty":None})
        self.assertFalse(provenance["signed_attestation"])

    def test_matching_build_record_binds_artifact_hash_but_is_not_attestation(self):
        wheel = self.wheel()
        record = self.build_record(wheel, dirty=True)
        provenance = verify.build_provenance(record, wheel, verify.sha256(wheel))
        self.assertEqual(provenance["status"], "matching_build_record")
        self.assertEqual(provenance["record_sha256"], verify.sha256(record))
        self.assertTrue(provenance["source"]["dirty"])
        self.assertEqual(provenance["github"]["run_attempt"], "2")
        self.assertFalse(provenance["signed_attestation"])

    def test_stale_artifact_hash_and_invalid_source_are_rejected(self):
        wheel = self.wheel()
        with self.assertRaisesRegex(AssertionError, "hash does not match"):
            verify.build_provenance(self.build_record(wheel, digest="f" * 64), wheel, verify.sha256(wheel))
        with self.assertRaisesRegex(AssertionError, "commit SHA"):
            verify.build_provenance(self.build_record(wheel, commit="HEAD"), wheel, verify.sha256(wheel))
        with self.assertRaisesRegex(AssertionError, "dirty must be a boolean"):
            verify.build_provenance(self.build_record(wheel, dirty="false"), wheel, verify.sha256(wheel))

    def test_source_observation_reports_unavailable_instead_of_clean(self):
        with patch.object(verify.subprocess, "check_output", side_effect=FileNotFoundError):
            source = verify.verification_source(self.root)
        self.assertIsNone(source["commit_sha"])
        self.assertIsNone(source["dirty"])
        with patch.object(verify.subprocess, "check_output", side_effect=["a" * 40 + "\n", " M scripts/verify_packages.py\n"]):
            self.assertTrue(verify.verification_source(self.root)["dirty"])

    def test_github_metadata_whitelists_run_context(self):
        self.assertEqual(verify.github_context({"GITHUB_RUN_ID":"123", "GITHUB_RUN_ATTEMPT":"2",
            "GITHUB_JOB":"python-wheel", "GITHUB_TOKEN":"secret"}),
            {"run_id":"123", "run_attempt":"2", "job":"python-wheel"})

    def test_dirty_flags_cannot_prove_identical_source_trees(self):
        clean = {"commit_sha":"a" * 40, "dirty":False}
        dirty = {"commit_sha":"a" * 40, "dirty":True}
        self.assertTrue(verify.source_unchanged(clean, clean))
        self.assertFalse(verify.source_unchanged(clean, dirty))
        self.assertIsNone(verify.source_unchanged(dirty, dirty))
        self.assertIsNone(verify.source_unchanged({"commit_sha":None,"dirty":None}, clean))

    def test_manifest_separates_build_commit_from_verifier_checkout(self):
        wheel = self.wheel()
        record = self.build_record(wheel)
        output = self.root / "manifest.json"
        source = {"role":"verifier_checkout", "commit_sha":"b" * 40, "dirty":True}
        result = {"package":verify.wheel_metadata(wheel), "verified_checks":["mocked_smoke"]}
        with patch.object(verify.sys, "argv", ["verify", "--wheel-dir", str(self.root), "--manifest", str(output), "--build-record", str(record)]), \
             patch.object(verify, "verification_source", return_value=source), \
             patch.object(verify, "verify_wheel", return_value=result), contextlib.redirect_stdout(io.StringIO()):
            verify.main()
        manifest = json.loads(output.read_text())
        self.assertEqual(manifest["artifacts"][wheel.name], verify.sha256(wheel))
        metadata = manifest["artifact_metadata"][wheel.name]
        self.assertEqual(metadata["package"]["version"], "0.2.0a1")
        self.assertEqual(metadata["build_provenance"]["source"]["commit_sha"], "a" * 40)
        self.assertEqual(manifest["verification_source"]["commit_sha"], "b" * 40)
        self.assertTrue(manifest["verification"]["passed"])

    def test_changed_artifact_cannot_receive_success_manifest(self):
        wheel = self.wheel()
        output = self.root / "manifest.json"
        def mutate(*args):
            wheel.write_bytes(b"changed after install")
            return {"package":{"name":"memweft","version":"0.2.0a1"}, "verified_checks":[]}
        with patch.object(verify.sys, "argv", ["verify", "--wheel-dir", str(self.root), "--manifest", str(output)]), \
             patch.object(verify, "verify_wheel", side_effect=mutate), \
             self.assertRaisesRegex(AssertionError, "changed during verification"):
            verify.main()
        self.assertFalse(output.exists())

    def test_smoke_failure_never_writes_success_manifest(self):
        self.wheel()
        output = self.root / "manifest.json"
        with patch.object(verify.sys, "argv", ["verify", "--wheel-dir", str(self.root), "--manifest", str(output)]), \
             patch.object(verify, "verify_wheel", side_effect=subprocess.CalledProcessError(1, "smoke")), \
             self.assertRaises(subprocess.CalledProcessError):
            verify.main()
        self.assertFalse(output.exists())


if __name__ == "__main__":
    unittest.main()
