#!/usr/bin/env python3
"""Install built SDK artifacts outside the checkout and exercise their native APIs.

Run after building a wheel and/or npm tarball. No package registry is contacted.
"""

import argparse
import hashlib
import json
import os
from pathlib import Path
import platform
import shutil
import subprocess
import sys
import tarfile
import tempfile
import venv
import zipfile


PYTHON_SMOKE = r'''
from pathlib import Path
import sqlite3
import sys

import memweft
from memweft import Memory
from memweft import _core

assert Path(memweft.__file__).resolve().is_relative_to(Path(sys.prefix).resolve())
assert Path(_core.__file__).resolve().is_relative_to(Path(sys.prefix).resolve())
database = Path("python-memory.db").resolve()
with Memory(str(database)) as memory:
    user = memory.user("package-smoke")
    user.remember("部署端口 17443", key="port")
    user.session("chat").add_message("user", "哪个端口？", event_id="question")
    context = user.session("chat").context(query="部署端口", max_facts=1)
    assert context.memories[0]["fact_key"] == "port"
    assert "哪个端口？" in context.text
with sqlite3.connect(database) as connection:
    assert connection.execute("SELECT version FROM memweft_recall_version").fetchone() == (3,)
with Memory(str(database)) as memory:
    assert memory.user("package-smoke").memories()[0]["value"] == "部署端口 17443"
print("installed Python wheel: native import, context and reopen passed")
'''


NODE_SMOKE = r'''
import assert from 'node:assert/strict';
import { resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Memory } from 'memweft';

assert.ok(fileURLToPath(import.meta.resolve('memweft'))
  .startsWith(resolve('node_modules', 'memweft') + sep));
const path = resolve('node-memory.db');
const memory = await Memory.open({path});
try {
  const user = memory.user('package-smoke');
  await user.remember('部署端口 17443', {key: 'port'});
  await user.session('chat').addMessage('user', '哪个端口？', {eventId: 'question'});
  const context = await user.session('chat').context({query: '部署端口', maxFacts: 1});
  assert.equal(context.memories[0].fact_key, 'port');
  assert.match(context.text, /哪个端口/);
} finally { memory.close(); }
const reopened = await Memory.open({path});
try {
  assert.equal((await reopened.user('package-smoke').memories())[0].value, '部署端口 17443');
} finally { reopened.close(); }
console.log('installed npm tarball: native import, context and reopen passed');
'''


def run(command: list[str], cwd: Path, environment: dict[str, str]) -> None:
    subprocess.run(command, cwd=cwd, env=environment, check=True)


def sole_artifact(directory: Path, pattern: str) -> Path:
    matches = sorted(directory.glob(pattern))
    if len(matches) != 1:
        raise ValueError(f"Expected one {pattern} in {directory}, found {len(matches)}")
    return matches[0].resolve(strict=True)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def verify_wheel(wheel: Path, temporary: Path, environment: dict[str, str]) -> None:
    with zipfile.ZipFile(wheel) as archive:
        files = archive.namelist()
    require(len([name for name in files if name.startswith("memweft/_core") and name.endswith((".so", ".pyd"))]) == 1,
            "wheel must contain exactly one native extension")
    require("memweft/__init__.py" in files, "wheel has no Python package")
    require(len([name for name in files if name.endswith(".dist-info/licenses/LICENSE")]) == 1,
            "wheel has no license text")
    require(not any("__pycache__" in name or name.endswith(".pyc") for name in files),
            "wheel includes generated bytecode")

    location = temporary / "python"
    location.mkdir()
    venv.create(location / "venv", with_pip=True)
    executable = location / "venv" / ("Scripts/python.exe" if os.name == "nt" else "bin/python")
    run([str(executable), "-m", "pip", "install", "--no-index", "--no-deps", str(wheel)], location, environment)
    run([str(executable), "-c", PYTHON_SMOKE], location, environment)


def verify_npm(tarball: Path, temporary: Path, environment: dict[str, str]) -> None:
    with tarfile.open(tarball, "r:gz") as archive:
        files = {member.name for member in archive.getmembers() if member.isfile()}
    for required in ("package/package.json", "package/LICENSE", "package/dist/index.js",
                     "package/dist/index.d.ts", "package/dist/langgraph.js",
                     "package/dist/langgraph.d.ts", "package/native/memweft.node"):
        require(required in files, f"npm package missing {required}")

    location = temporary / "node"
    location.mkdir()
    (location / "package.json").write_text('{"private":true,"type":"module"}\n', encoding="utf-8")
    (location / "smoke.mjs").write_text(NODE_SMOKE, encoding="utf-8")
    npm = shutil.which("npm")
    node = shutil.which("node")
    if not npm or not node:
        raise RuntimeError("Node.js and npm are required for npm package verification")
    # The addon is already inside the tarball; ignore hooks and optional peers.
    run([npm, "install", "--offline", "--ignore-scripts", "--no-audit", "--no-fund",
         "--omit=optional", "--omit=peer", str(tarball)], location, environment)
    run([node, "smoke.mjs"], location, environment)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wheel-dir", type=Path, help="directory containing exactly one built wheel")
    parser.add_argument("--npm-dir", type=Path, help="directory containing exactly one built npm tarball")
    parser.add_argument("--manifest", type=Path, help="write target and artifact hashes for distribution")
    args = parser.parse_args()
    if not args.wheel_dir and not args.npm_dir:
        parser.error("pass --wheel-dir and/or --npm-dir")
    wheel = sole_artifact(args.wheel_dir, "*.whl") if args.wheel_dir else None
    tarball = sole_artifact(args.npm_dir, "*.tgz") if args.npm_dir else None
    environment = {key: value for key, value in os.environ.items()
                   if key not in ("PYTHONPATH", "PYTHONHOME", "PYTHONOPTIMIZE", "VIRTUAL_ENV", "NODE_PATH", "PIP_PREFIX")}
    environment["PIP_NO_INDEX"] = "1"
    environment["PIP_NO_CACHE_DIR"] = "1"
    environment["PIP_DISABLE_PIP_VERSION_CHECK"] = "1"
    with tempfile.TemporaryDirectory(prefix="memweft-package-check-") as directory:
        temporary = Path(directory)
        if wheel:
            verify_wheel(wheel, temporary, environment)
        if tarball:
            # Keep npm's cache within the disposable test directory too.
            environment["npm_config_cache"] = str(temporary / "npm-cache")
            verify_npm(tarball, temporary, environment)
    if args.manifest:
        host = {"os": platform.system(), "machine": platform.machine()}
        if platform.system() == "Linux":
            host["libc"] = platform.libc_ver()
        manifest = {"host": host, "artifacts": {}}
        if wheel:
            manifest["python"] = f"{sys.version_info.major}.{sys.version_info.minor}"
            manifest["artifacts"][wheel.name] = sha256(wheel)
        if tarball:
            node = shutil.which("node")
            manifest["node"] = json.loads(subprocess.check_output(
                [node, "-p", "JSON.stringify({platform:process.platform,arch:process.arch,napi:process.versions.napi})"],
                cwd=tarball.parent, env=environment, text=True))
            manifest["artifacts"][tarball.name] = sha256(tarball)
        args.manifest.parent.mkdir(parents=True, exist_ok=True)
        args.manifest.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"verified": True, "wheel": wheel is not None, "npm": tarball is not None}))


if __name__ == "__main__":
    main()
